library(Seurat)
library(cowplot)
library(patchwork)
library(dplyr)
library(ggplot2)
mac <- readRDS("Mac_celltype.rds")
DimPlot(mac,label = T)
data <- AverageExpression(mac,group.by = "celltype3")
data <- t(data$integrated)
a <- dist(data,method = "euclidean")
hc <- hclust(a,method = "average")
png("cluster.png")
plot(hc,hang = -0.1,cex=0.7)
dev.off()